#ifndef DATA_H
#define DATA_H

typedef enum
{
  DIRECTORYIDX = 0,
  INSTANCEIDX = 1,
  IROOTIDX = 2,
  ISYSTEMIDX = 3,
  INACTIVEIDX = 4,
  FRAGMENTIDX = 5,
  ELO_CPICIDX = 6,
  IAPPLICATIONIDX = 7,
  GAZ_CPICIDX = 8,
  MEC_CPICIDX = 9,
  BOOT_KERNELIDX = 10,
  BOXIDX = 11,
  STARPORTIDX = 12,
  BANKIDX = 13,
  BANK_TRANSIDX = 14,
  PERSONNELIDX = 15,
  CREWMEMBERIDX = 16,
  ASSIGN_CREWIDX = 17,
  SHIP_CONFIGIDX = 18,
  TRADE_DEPOTIDX = 19,
  SHIPIDX = 20,
  MYS_CPICIDX = 21,
  TIMEIDX = 22,
  STARSYSTEMIDX = 23,
  STARIDX = 24,
  VESSELIDX = 25,
  ELEMENTIDX = 26,
  MESSAGEIDX = 27,
  ARTIFACTIDX = 28,
  PROJECTILEIDX = 29,
  NOM_CPICIDX = 30,
  SPE_CPICIDX = 31,
  PLANETIDX = 32,
  THR_CPICIDX = 33,
  OPERATIONSIDX = 34,
  NOTICEIDX = 35,
  EVALUATIONIDX = 36,
  VEL_CPICIDX = 37,
  VPR_CPICIDX = 38,
  MIN_CPICIDX = 39,
  SPECIMENIDX = 40,
  RUINIDX = 41,
  TVEHICLEIDX = 42,
  BIO_DATAIDX = 43,
  TPORT_PICIDX = 44,
  FLUX_NODEIDX = 45,
  NEBULAIDX = 46,
  CAPT_LOGIDX = 47,
  STRINGIDX = 48,
  BPORT_PICIDX = 49,
  PHRASECONTRLIDX = 50,
  SUBJECTIDX = 51,
  ORIGINATORIDX = 52,
  MESSAGE_IDX = 53,
  SPLASHIDX = 54,
  TEXTIDX = 55,
  SCROLL_TEXTIDX = 56,
  ANALYZE_TEXTIDX = 57,
  BUTTONSIDX = 58,
  BLT_HEADIDX = 59,
  MED_PICIDX = 60,
  ENCOUNTERIDX = 61,
  ICON1_1IDX = 62,
  ICON1_2IDX = 63,
  ICON1_4IDX = 64,
  ICON_NAMEIDX = 65,
  DPART_OVIDX = 66,
  REGIONSIDX = 67,
  CREATUREIDX = 68,
  PHAZESIDX = 69,
  CHKFLIGHT_OVIDX = 70,
  FRACT_OVIDX = 71,
  ICONP_OVIDX = 72,
  SITE_OVIDX = 73,
  HYPERMSG_OVIDX = 74,
  GPOLYIDX = 75,
  FACETIDX = 76,
  VERTEXIDX = 77,
  BLT_OVIDX = 78,
  MISC_OVIDX = 79,
  BANK_OVIDX = 80,
  ASSCREW_OVIDX = 81,
  PERSONNEL_OVIDX = 82,
  SHIPGRPH_OVIDX = 83,
  CONFIG_OVIDX = 84,
  TDEPOT_OVIDX = 85,
  EDIT_OVIDX = 86,
  PORTMENU_OVIDX = 87,
  VITA_OVIDX = 88,
  HP_OVIDX = 89,
  LP_OVIDX = 90,
  SENT_OVIDX = 91,
  TV_OVIDX = 92,
  COMM_OVIDX = 93,
  COMMSPEC_OVIDX = 94,
  SEED_OVIDX = 95,
  LISTICONSIDX = 96,
  MOVE_OVIDX = 97,
  ENGINEERIDX = 98,
  DOCTORIDX = 99,
  ORBIT_OVIDX = 100,
  CAPTAINIDX = 101,
  SCIENCEIDX = 102,
  NAVIGATRIDX = 103,
  SHIPBUTTONSIDX = 104,
  _MAP_OVIDX = 105,
  HYPER_OVIDX = 106,
  ANALYZE_OVIDX = 107,
  LAUNCH_OVIDX = 108,
  FLUX_EFFECTIDX = 109,
  OP_OVIDX = 110,
  ITEMS_OVIDX = 111,
  LSYSICONIDX = 112,
  MSYSICONIDX = 113,
  SSYSICONIDX = 114,
  BEHAV_OVIDX = 115,
  CMAPIDX = 116,
  INSTALLIDX = 117,
  HEAL_OVIDX = 118,
  REPAIR_OVIDX = 119,
  GAME_OVIDX = 120,
  PLSET_OVIDX = 121,
  MAPS_OVIDX = 122,
  VES_BLTIDX = 123,
  STORM_OVIDX = 124,
  HUM_PICIDX = 125,
  VEL_PICIDX = 126,
  THR_PICIDX = 127,
  ELO_PICIDX = 128,
  AND_PICIDX = 129,
  COMPOUNDSIDX = 130,
  IT_OVIDX = 131,
  COMBAT_OVIDX = 132,
  DAMAGE_OVIDX = 133,
  LAND_OVIDX = 134,
  PSTATSIDX = 135,
  SAVEIDX = 136,
  MUSICIDX = 137,
  EARTHIDX = 138,
  STP_OVIDX = 139,
  GALAXYIDX = 140,
  CREDITSIDX = 141,
  COP_CPICIDX = 142,
  FONTSIDX = 143,
} FILEINDEXES;

char *BOX_STRINGS[] =
{
  "                ",
  "SECS            ",
  "SEC             ",
  "STARSYSTEMS     ",
  "ORBIT           ",
  "                ",
  "ENVIRONMENTAL   ",
  "MERCATORS       ",
  "-CONTOUR-REGION ",
  "POSITIVE-OBJECTS",
  "ELEMENTS        ",
  "LIFEFORMS       ",
  "MOBILE          ",
  "SESSILE         ",
  "SPECIMENS       ",
  "ARTIFACTS       ",
  "RUINS           ",
  "MESSAGES        ",
  "NEGATIVE-OBJECTS",
  "OLD-CONTOURS    ",
  "CONTOUR-REGION  ",
  "CONTOURS        ",
  "ITEMS FOR SALE  ",
  "STARSHIP HOLD   ",
  "TILES           ",
  "FLUX-NODES      ",
  "GAS-CLOUDS      ",
  "ENCOUNTERS      ",
  "NOTICES         ",
  "PICTURES        ",
  "ALIEN-PICS      ",
  "SENSOR-PICS     ",
  "STARPORT-PICS   ",
  "TITLE-PICS      ",
  "WORDS           ",
  "PHRASES         ",
  "COMMUNICATIONS  ",
  "LIFEFORM-PICS   ",
  "BIO-DATA        ",
  "SPECIAL PHRASES ",
  "TERRAIN VEHICLE ",
  "SCROLL-TEXTS    ",
  "GEN-PHRASE      ",
  "CAPTAIN'S LOG   ",
  "PLANET SURFACE  ",
  "EVALUATIONS     ",
  "SUPER BOX       ",
  "RANDOM MESSAGES ",
  "DEBRIS          ",
  "TEMPORARY       ",
  "END OF LIST     ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                "
};

char *BANKTRANS_STRINGS[] =
{
  "FINE",
  "SHIP CONFIGURATION",
  "TRADE DEPOT",
  "BONUS",
  "PERSONNEL",
  "INTEREST",
  "GAME PURCHASE"
};

char *ANALYZETEXT_STRINGS[] =
{
  "ANALYSIS OF THIS ARTIFACT HAS REVEALEDVERY LITTLE OF INTEREST. IT HAS SLIGHTVALUE AS AN ALIEN CURIO, BUT OTHERWISEIS TOTALLY USELESS TO US.                                                   ",
  "OUR GUESS IS THIS IS SOME DEVICE OF   THE ANCIENTS. BEYOND THAT, WE CAN'T   TELL.                                                                                                             ",
  "THIS APPEARS TO BE A BOMB OF SOME     SORT. THE TYPE IS UNFAMILIAR. TO      ACTIVATE IT, YOU MUST DROP IT.                                                                                    ",
  "THIS IS CRAFTED OF ENDURIUM. IT       DOESN'T APPEAR TO HAVE ANY FUNCTION   OTHER THAN BEING DECORATIVE.                                                                                      ",
  "THIS WAS FOUND IN THE UNDERGROUND     COLONY. WE'RE NOT SURE WHAT IS DOES.  WE THINK IT HAS SOMETHING TO DO WITH  COMMUNICATION.                                                              ",
  "THIS DEVICE WILL PROJECT A SHIELD     AROUND YOUR TERRAIN VEHICLE WHICH     MAKES IT DIFFICULT FOR DANGEROUS      LIFEFORMS TO ATTACK YOU.                                                    ",
  "THIS APPEARS TO BE A DEVICE OF THE OLDEMPIRE THAT PROJECTS AN ENHANCED LASERSHIELD AROUND A SPACESHIP.                                                                                        ",
  "THIS IS A DEVICE OF THE OLD EMPIRE    THAT PROJECTS A FIELD WHICH DOUBLES   THE ENERGY EFFICIENCY OF A SHIP'S     ENGINES.                                                                    ",
  "THIS IS AN ANCIENT SHIP NAVIGATIONAL  AID. IT WILL IDENTIFY ANY NEARBY      CONTINUUM FLUX.                                                                                                   ",
  "THIS APPEARS TO BE A 4-DIMENSIONAL    PUZZLE COMPOSED OF MANY MULTI-COLORED CUBES. ITS USE PRODUCES AN OVER-      WHELMING FEELING OF ATARAXIA.                                               ",
  "THIS ARTIFACT SEEMS TO BE A CLOAKING  DEVICE. AS FAR AS WE CAN TELL IT      SHOULD OPERATE AUTOMATICALLY DURING   COMBAT.                                                                     ",
  "WE CAN'T FIGURE OUT EXACTLY WHAT THIS IS. IT SLICES, IT DICES, IT EVEN MAKESJULIENNE FRIES!                                                                                                   ",
  "THIS SEEMS TO BE AN ORBITAL SCANNER OFSOME SORT. WE'RE NOT SURE WHAT IT'S   TUNED TO LOCATE THOUGH.                                                                                           ",
  "THIS IS SOME SORT OF TRANSMITTER. IT  IS BROADCASTING CONTINUALLY ON SEVERALBANDS. THE NET EFFECT SHOULD BE THAT  IT WILL ATTRACT THE ATTENTION OF      ANYONE IN THE AREA.                   ",
  "THIS SEEMS TO BE A DEVICE OF THE      ANCIENTS, BUT WE CAN'T FIGURE OUT WHATIT DOES. IT CONTAINS A TREMENDOUS     AMOUNT OF ENERGY.                                                           ",
  "THE REMAINS OF AN OLDER, INFERIOR     MODEL TERRAIN VEHICLE, DOUBTLESSLY    LEFT HERE BY SOME PRIOR EXPLORATION   PARTY TOO FOOLISH TO RETURN TO THEIR  SHIP BEFORE EXHAUSTING THEIR ENERGY.  "
};

char *SPECIMEN_STRINGS[] =
{
  "                ",
  "AMORPHOUS.......",
  "IRREGULAR.......",
  "SPHERICAL.......",
  "RADIAL..........",
  "BILATERAL.......",
  "AMOEBOID........",
  "TREE-LIKE.......",
  "BALLOON-LIKE....",
  "ANTELOPE-LIKE...",
  "BIRD-LIKE.......",
  "DINOSAUR-LIKE...",
  "HUMANOID........",
  "INSECTOID.......",
  "PLANT-LIKE......",
  "BEAR-LIKE.......",
  "REPTILIAN.......",
  "RODENT-LIKE.....",
  "SLUG-LIKE.......",
  "SNAIL-LIKE......",
  "SNAKE-LIKE......",
  "SPIDER-LIKE.....",
  "TURTLE-LIKE.....",
  "ROCK-LIKE.......",
  "FUNGOID.........",
  "EWOK-LIKE.......",
  "STARFISH-LIKE...",
  "ANEMONE-LIKE...."
};

#endif
